-- ES Network account foundation for Supabase
-- Apply through the connected Supabase project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  member_id text not null unique,
  display_name text not null check (char_length(display_name) between 2 and 40),
  role text not null default 'member' check (role in ('member','staff','admin','owner')),
  status text not null default 'active' check (status in ('active','suspended','banned')),
  credits bigint not null default 0 check (credits >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null,
  balance_after bigint,
  reason text not null,
  source text not null default 'system',
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, member_id, display_name)
  values (
    new.id,
    'ESN-' || upper(substr(replace(new.id::text, '-', ''), 1, 8)),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute procedure public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.credit_transactions enable row level security;

drop policy if exists "members read own profile" on public.profiles;
create policy "members read own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "members update own profile" on public.profiles;
create policy "members update own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "members read own credit history" on public.credit_transactions;
create policy "members read own credit history"
on public.credit_transactions for select
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.profiles from anon;
grant select on table public.profiles to authenticated;
grant update (display_name) on table public.profiles to authenticated;

revoke all on table public.credit_transactions from anon;
grant select on table public.credit_transactions to authenticated;

-- Important: credits, role, status, and admin actions remain server-controlled.
-- Do not grant browser clients UPDATE privileges on those columns.
