export const VERIFIED_REVIEWS = [
  { name:'Avery', handle:'@buildwithavery', rating:'★5/5', category:'Fortnite Coaching', text:'Coach reviewed my VODs, fixed positioning habits, and gave daily drills. I felt ranked improvement within days.' },
  { name:'Riley', handle:'@rileywins', rating:'★5/5', category:'Fortnite Coaching', text:'Session focused on live match decisions, not generic tips. My rotations and late-game choices improved fast.' },
  { name:'Cameron', handle:'@cameronfps', rating:'★5/5', category:'Fortnite Coaching', text:'I got direct feedback on mechanics and piece-control timing. Every note was practical for scrims.' },
  { name:'Hayden', handle:'@haydenbuilds', rating:'★5/5', category:'Fortnite Coaching', text:'Coach broke down fight mistakes and built a zone-by-zone plan. I left more confident for tournaments.' },
  { name:'Rowan', handle:'@rowancompetitive', rating:'★5/5', category:'Fortnite Coaching', text:'In-game examples made everything click quickly. The coaching matched my playstyle and rank goals.' },
  { name:'Dakota', handle:'@dakotagrinds', rating:'★5/5', category:'Fortnite Coaching', text:'Great one-on-one session with clear aim and movement drills. I left with a focused practice routine.' },
  { name:'Lane', handle:'@laneclutch', rating:'★5/5', category:'Fortnite Coaching', text:'No overcomplication—just direct build-fight, peek, and timing coaching I could use in arena right away.' },
  { name:'Morgan', handle:'@morganrankup', rating:'★5/5', category:'Fortnite Coaching', text:'Plan was built around my current level with clear next steps for mechanics and game sense.' },
  { name:'Phoenix', handle:'@phoenixfn', rating:'★5/5', category:'Fortnite Coaching', text:'Coach spotted weak points quickly and gave repeatable drills. My decision-making improved that week.' },
  { name:'Noah', handle:'@noahtakesheight', rating:'★5/5', category:'Fortnite Coaching', text:'Everything was taught step by step, from early routes to end-game pressure. It felt truly competitive.' },
  { name:'Remy', handle:'@remyzonewars', rating:'★5/5', category:'Fortnite Coaching', text:'Detailed VOD feedback and clear targets made my next practice block far more efficient.' },
  { name:'Sage', handle:'@sagegrindset', rating:'★5/5', category:'Fortnite Coaching', text:'Mechanics and match planning stayed outcome-focused. I finally had a consistent routine after one session.' },

  { name:'Jordan', handle:'@jordyclips', rating:'★5/5', category:'Editing', text:'Fast communication and a polished cut with clean sync, smooth transitions, and pacing that matched my brief.' },
  { name:'Skyler', handle:'@skylercreates', rating:'★5/5', category:'Editing', text:'Editor nailed the energy for my channel. The cut came back sharp, clean, and ready to post.' },
  { name:'Parker', handle:'@parkerplays', rating:'★5/5', category:'Editing', text:'Ordering was simple, and the final gaming edit delivered exactly promised—clean structure and strong flow.' },
  { name:'Quinn', handle:'@quinnmotion', rating:'★5/5', category:'Editing', text:'Transitions were smooth, pacing stayed tight, and the final cut looked far more professional.' },
  { name:'Sawyer', handle:'@sawyerstudio', rating:'★5/5', category:'Editing', text:'Communication stayed consistent and quality felt premium. The project moved fast without losing polish.' },
  { name:'Taylor', handle:'@tayloredits', rating:'★5/5', category:'Editing', text:'Quick turnaround with a polished gaming edit. I needed almost no changes before posting.' },
  { name:'Alex', handle:'@alexcreativehub', rating:'★5/5', category:'Editing', text:'Final cut matched the exact mood and style I requested. Strong communication and upload-ready delivery.' },
  { name:'Jamie', handle:'@jamievisuals', rating:'★5/5', category:'Editing', text:'Great pacing and clean polish from start to finish. The whole project felt premium.' },
  { name:'Drew', handle:'@drewmontage', rating:'★5/5', category:'Editing', text:'Asked for a high-energy montage and got clean beat sync, strong transitions, and quick delivery.' },
  { name:'Harper', handle:'@harperreels', rating:'★5/5', category:'Editing', text:'Updates stayed clear throughout, and notes were handled quickly. Final cut was fully upload-ready.' },
  { name:'Micah', handle:'@micahanimecuts', rating:'★5/5', category:'Editing', text:'I asked for anime-style impact pacing and got exactly that—stylish timing with clear storytelling.' },
  { name:'River', handle:'@riverpostfx', rating:'★5/5', category:'Editing', text:'Premium quality, on-schedule delivery, and an easy workflow. The final piece had the polish my brand needed.' },

  { name:'Mason', handle:'@masoncommunity', rating:'★5/5', category:'Discord Server Setup', text:'Our server came back organized with cleaner categories, permissions, and onboarding. Members navigate it much faster now.' },
  { name:'Blake', handle:'@blakehub', rating:'★5/5', category:'Discord Server Setup', text:'New channel structure and role permissions made the community feel instantly more professional.' },
  { name:'Emerson', handle:'@emersonserver', rating:'★5/5', category:'Discord Server Setup', text:'Channel flow and staff control are much better. New members now know where to start.' },
  { name:'Finley', handle:'@finleyguild', rating:'★5/5', category:'Discord Server Setup', text:'Staff and member channels are finally easy to navigate. Confusion dropped right away.' },
  { name:'Reese', handle:'@reeseteam', rating:'★5/5', category:'Discord Server Setup', text:'Permissions, staff channels, and categories were rebuilt in a way that makes moderation easier daily.' },
  { name:'Casey', handle:'@caseycommunitylead', rating:'★5/5', category:'Discord Server Setup', text:'The server is now cleaner for members and far easier for our team to run.' },
  { name:'Kendall', handle:'@kendallops', rating:'★5/5', category:'Discord Server Setup', text:'Flow is cleaner, onboarding is smoother, and new members know exactly where to go.' },
  { name:'Peyton', handle:'@peytonmods', rating:'★5/5', category:'Discord Server Setup', text:'Roles, channel map, and onboarding were redesigned so members understood the server immediately.' },
  { name:'Logan', handle:'@loganlfg', rating:'★5/5', category:'Discord Server Setup', text:'We needed a competitive community structure and got one—clean, scalable, and easy to maintain.' },
  { name:'Ari', handle:'@ariserverops', rating:'★5/5', category:'Discord Server Setup', text:'The setup balanced visual polish with real function. Staff workflows are smoother and key channels are easy to find.' },
  { name:'Shawn', handle:'@shawncommunityhq', rating:'★5/5', category:'Discord Server Setup', text:'Our live community was reorganized with minimal disruption. The server now feels premium and easier to use.' },
]
